/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS;

import static java.lang.Integer.parseInt;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class booking extends javax.swing.JFrame {

    /**
     * Creates new form booking
     */
    public booking() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bookingfacility = new javax.swing.JComboBox();
        bookingname = new javax.swing.JTextField();
        bookingbedtype = new javax.swing.JComboBox();
        hostbtn = new javax.swing.JButton();
        bookingsubmitbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bookingaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bookingphone = new javax.swing.JTextField();
        bookingamount = new javax.swing.JLabel();
        bookingnid = new javax.swing.JTextField();
        bookingpaymentbtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bookingpaymentstatus = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bookingoutdate = new org.jdesktop.swingx.JXDatePicker();
        bookingindate = new org.jdesktop.swingx.JXDatePicker();
        bookingroomcount = new javax.swing.JTextField();
        bookingpayacno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Booking");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 120, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 130, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("No of Room");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 160, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Out Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, 260, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("In Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(450, 210, 80, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Extra Facilities");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 310, 100, 30);

        bookingfacility.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1" }));
        bookingfacility.setSelectedIndex(-1);
        bookingfacility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingfacilityActionPerformed(evt);
            }
        });
        jPanel1.add(bookingfacility);
        bookingfacility.setBounds(560, 310, 180, 30);

        bookingname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingnameActionPerformed(evt);
            }
        });
        jPanel1.add(bookingname);
        bookingname.setBounds(150, 130, 160, 30);

        bookingbedtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Delux", "Super Delux", "Condo", "Dual Bed", "Suit" }));
        bookingbedtype.setSelectedIndex(-1);
        bookingbedtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingbedtypeActionPerformed(evt);
            }
        });
        jPanel1.add(bookingbedtype);
        bookingbedtype.setBounds(560, 110, 180, 30);

        hostbtn.setBackground(new java.awt.Color(255, 255, 255));
        hostbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hostbtn.setText("<");
        hostbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostbtnActionPerformed(evt);
            }
        });
        jPanel1.add(hostbtn);
        hostbtn.setBounds(10, 10, 60, 30);

        bookingsubmitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookingsubmitbtn.setText("Submit");
        bookingsubmitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingsubmitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookingsubmitbtn);
        bookingsubmitbtn.setBounds(370, 410, 160, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Bed Type");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(450, 110, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Address");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 180, 80, 30);

        bookingaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingaddressActionPerformed(evt);
            }
        });
        jPanel1.add(bookingaddress);
        bookingaddress.setBounds(150, 180, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Phone");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 230, 80, 30);

        bookingphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingphoneActionPerformed(evt);
            }
        });
        jPanel1.add(bookingphone);
        bookingphone.setBounds(150, 230, 160, 30);

        bookingamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookingamount.setText("-----------------");
        jPanel1.add(bookingamount);
        bookingamount.setBounds(630, 10, 100, 20);

        bookingnid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingnidActionPerformed(evt);
            }
        });
        jPanel1.add(bookingnid);
        bookingnid.setBounds(150, 290, 160, 30);

        bookingpaymentbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookingpaymentbtn.setText("Payment");
        bookingpaymentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingpaymentbtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookingpaymentbtn);
        bookingpaymentbtn.setBounds(550, 410, 160, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("NID");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 290, 80, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Total:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(500, 10, 90, 20);

        bookingpaymentstatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookingpaymentstatus.setText("------------------");
        jPanel1.add(bookingpaymentstatus);
        bookingpaymentstatus.setBounds(630, 50, 100, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("A/C No.");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 400, 100, 30);
        jPanel1.add(bookingoutdate);
        bookingoutdate.setBounds(560, 260, 170, 30);
        jPanel1.add(bookingindate);
        bookingindate.setBounds(560, 210, 170, 30);
        jPanel1.add(bookingroomcount);
        bookingroomcount.setBounds(560, 160, 180, 30);
        jPanel1.add(bookingpayacno);
        bookingpayacno.setBounds(150, 400, 150, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Payment Status:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(500, 50, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingfacilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingfacilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingfacilityActionPerformed

    private void bookingnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingnameActionPerformed

    private void bookingbedtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingbedtypeActionPerformed
        String bedtype = bookingbedtype.getSelectedItem().toString();
        System.out.println(bedtype);
    }//GEN-LAST:event_bookingbedtypeActionPerformed

    private void hostbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostbtnActionPerformed
        
        service srvc=new service();
        srvc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hostbtnActionPerformed

    private void bookingsubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingsubmitbtnActionPerformed
        try {
            String bn = bookingname.getText();
            String badd = bookingaddress.getText();
            String bp = bookingphone.getText();
            String bnid = bookingnid.getText();
            String cmd = "insert into cust_info (Name,Address,Phone,NID) values ('"+bn+"','"+badd+"','"+bp+"','"+bnid+"')";
            dbconnection.getqueryupdate(cmd);
            
            String rcmd = "select ID from cust_info where Name = '"+bn+"' and NID = '"+bnid+"'";
            ResultSet grs = dbconnection.getresult(rcmd);
            String cust_id=null;
            while(grs.next()){
                cust_id = grs.getString("ID");
            }
            System.out.println(cust_id);
            
            String bedtype = bookingbedtype.getSelectedItem().toString();
            System.out.println(bedtype);
            
            
            if(bedtype.equalsIgnoreCase("delux"))bedtype="D";
            else if(bedtype.equalsIgnoreCase("super delux"))bedtype="SD";
            else if(bedtype.equalsIgnoreCase("condo"))bedtype="C";
            else if(bedtype.equalsIgnoreCase("dual bed"))bedtype="DB";
            else if(bedtype.equalsIgnoreCase("suit"))bedtype="ST";
            System.out.println(bedtype);
            int nroom = parseInt(bookingroomcount.getText());
            Date in = bookingindate.getDate();
            Date out = bookingoutdate.getDate();
            DateFormat convrt = new SimpleDateFormat("yyyy-MM-dd");
            
            String indate = convrt.format(in);
            String outdate = convrt.format(out);
            String xf = bookingfacility.getSelectedItem().toString();
            String pay = String.valueOf((3000*nroom));
            String rcmd1 = "select ID from service where bed_type = '"+bedtype+"' and ext_fac = '"+xf+"'";
            String serv_id=null; 
             grs = dbconnection.getresult(rcmd1);
             while(grs.next()){
                 serv_id = grs.getString("ID");
             }
            System.out.println(serv_id);
            
            String cmdm = "insert into record (customer_id,in_date,service_id,room_no,payment) values('"+cust_id+"','"+indate+"','"+serv_id+"','"+nroom+"','"+pay+"')";
            dbconnection.getqueryupdate(cmdm);
            String cmdm2 = "select ID from record where in_date = '"+indate+"' and customer_id = '"+cust_id+"'";
            String recd_id = null;
            grs = dbconnection.getresult(cmdm2);
            
            while(grs.next()){
                recd_id = grs.getString("ID");
            }
            System.out.println(recd_id);
            
            String stat = "booked";
            
            String pbcmd = "insert into prebook (rec_id,out_date,status) values ('"+recd_id+"','"+outdate+"','"+stat+"')";
            dbconnection.getqueryupdate(pbcmd);
            JOptionPane.showMessageDialog(this, "Process Complete!");
        } catch (SQLException ex) {
            Logger.getLogger(booking.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed :( ");
        }
        
    }//GEN-LAST:event_bookingsubmitbtnActionPerformed

    private void bookingaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingaddressActionPerformed

    private void bookingphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingphoneActionPerformed

    private void bookingnidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingnidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingnidActionPerformed

    private void bookingpaymentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingpaymentbtnActionPerformed
        
    }//GEN-LAST:event_bookingpaymentbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookingaddress;
    private javax.swing.JLabel bookingamount;
    private javax.swing.JComboBox bookingbedtype;
    private javax.swing.JComboBox bookingfacility;
    private org.jdesktop.swingx.JXDatePicker bookingindate;
    private javax.swing.JTextField bookingname;
    private javax.swing.JTextField bookingnid;
    private org.jdesktop.swingx.JXDatePicker bookingoutdate;
    private javax.swing.JTextField bookingpayacno;
    private javax.swing.JButton bookingpaymentbtn;
    private javax.swing.JLabel bookingpaymentstatus;
    private javax.swing.JTextField bookingphone;
    private javax.swing.JTextField bookingroomcount;
    private javax.swing.JButton bookingsubmitbtn;
    private javax.swing.JButton hostbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
